--------------------------------------------------------
--  Fichier créé - lundi-mai-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_ROLES
--------------------------------------------------------

  CREATE TABLE "MOMEN"."USER_ROLES" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 CHAR), 
	"ROLE" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MOMEN"."USERS" 
   (	"USERNAME" VARCHAR2(20 CHAR), 
	"PASSWORD" VARCHAR2(60 CHAR), 
	"ENABLED" NUMBER(1,0) DEFAULT 1, 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR" ;
 

   COMMENT ON COLUMN "MOMEN"."USERS"."USERNAME" IS 'le matricule est utilisée pour ce champs';
 
   COMMENT ON COLUMN "MOMEN"."USERS"."ENABLED" IS '0 : not enabled, 1 : enabled';
--------------------------------------------------------
--  DDL for Index USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOMEN"."USER_ROLES_PK" ON "MOMEN"."USER_ROLES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR" ;
--------------------------------------------------------
--  DDL for Index USERS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOMEN"."USERS_PK1" ON "MOMEN"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR" ;
--------------------------------------------------------
--  Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MOMEN"."USER_ROLES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "MOMEN"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MOMEN"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "MOMEN"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "MOMEN"."USERS" MODIFY ("ENABLED" NOT NULL ENABLE);
 
  ALTER TABLE "MOMEN"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "D_OSCAR"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ROLES
--------------------------------------------------------

  ALTER TABLE "MOMEN"."USER_ROLES" ADD CONSTRAINT "USER_ROLES_FK1" FOREIGN KEY ("USERNAME")
	  REFERENCES "MOMEN"."USERS" ("USERNAME") ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_ROLES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MOMEN"."USER_ROLES_TRG" 
BEFORE INSERT ON USER_ROLES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MOMEN"."USER_ROLES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MOMEN"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "MOMEN"."USERS_TRG" ENABLE;
